repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: .*drawio$
  - id: check-yaml
    args: [--allow-multiple-documents]
    additional_dependencies: [ruamel_yaml]
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: detect-private-key
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: check-toml
  - id: check-json
    exclude: ^.devcontainer/
  - id: pretty-format-json
    args: [--autofix]
    exclude: ^.*appsettings.*\.json$

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
  - id: terraform_fmt
  - id: terragrunt_fmt

- repo: https://github.com/jackdewinter/pymarkdown
  rev: 0.9.16
  hooks:
  - id: pymarkdown
    additional_dependencies: [wcwidth, ruamel_yaml]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/kamadorueda/alejandra
  # TODO: When this issue is resolved, switch to newer tag ref
  # Ref: https://github.com/kamadorueda/alejandra/issues/388
  rev: 1.3.0
  hooks:
  - id: alejandra

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
  - id: check-renovate
    additional_dependencies: [json5, urllib3]
  - id: check-github-actions

- repo: https://github.com/hadolint/hadolint
  rev: v2.12.1-beta
  hooks:
  - id: hadolint
- repo: local
  hooks:
  - id: copy-repeated-files
    name: Copy files
    entry: copy-repeated-files.sh
    language: script
    always_run: true
    pass_filenames: false
